###################################################################################################
###                  THIS IS A REUSABLE WORKFLOW TO BUILD SCALA WITH CHOCOLATEY                 ###
### HOW TO USE:                                                                                 ###
###                                                                                             ###
### NOTE:                                                                                       ###
###                                                                                             ###
###################################################################################################


name: Build 'scala' Chocolatey Package

on:
  push:

env:
  CHOCOLATEY-REPOSITORY: chocolatey-pkgs

jobs:
  s:
      runs-on: windows-latest
      steps:
         - run: choco install scala
         - run: scala --version
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Replace the version placeholder
        uses: richardrigutins/replace-in-files@v2
        with:
          files: ./pkgs/chocolatey/scala.nuspec
          search-text: '@LAUNCHER_VERSION@'
          replacement-text: 3.6.0-RC1
      - name: Replace the URL placeholder
        uses: richardrigutins/replace-in-files@v2
        with:
          files: ./pkgs/chocolatey/tools/chocolateyInstall.ps1
          search-text: '@LAUNCHER_URL@'
          replacement-text: https://chara.epfl.ch/~remmal/scala.msi
      - name: Build the Chocolatey package (.nupkg)
        run: choco pack ./pkgs/chocolatey/scala.nuspec --out ./pkgs/chocolatey
      - name: Upload the Chocolatey package to GitHub
        uses: actions/upload-artifact@v4
        with:
          name: scala.nupkg
          path: ./pkgs/chocolatey/scala.*.nupkg
          if-no-files-found: error
  test:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download the 'nupkg' from GitHub Artifacts
        uses: actions/download-artifact@v4
        with:
          name: scala.nupkg
          path: ${{ env.CHOCOLATEY-REPOSITORY }}
      - name : Install the `scala` package with Chocolatey
        run  : choco install scala --source "${{ env.CHOCOLATEY-REPOSITORY }}" --pre # --pre since we might be testing non-stable releases
        shell: pwsh
      - name : Test the scala command
        run  : scala --version
        shell: pwsh
